package com.cascv.oas.server.energy.mapper;

import com.cascv.oas.server.energy.model.EnergySourcePoint;
import com.cascv.oas.server.energy.model.EnergySourcePointExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EnergySourcePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    long countByExample(EnergySourcePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int deleteByExample(EnergySourcePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int insert(EnergySourcePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int insertSelective(EnergySourcePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    List<EnergySourcePoint> selectByExample(EnergySourcePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    EnergySourcePoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") EnergySourcePoint record, @Param("example") EnergySourcePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByExample(@Param("record") EnergySourcePoint record, @Param("example") EnergySourcePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByPrimaryKeySelective(EnergySourcePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_source_point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByPrimaryKey(EnergySourcePoint record);
}