package com.cascv.oas.server.energy.mapper;

import com.cascv.oas.server.energy.model.EnergyBall;
import com.cascv.oas.server.energy.model.EnergyBallExample;
import com.cascv.oas.server.energy.vo.EnergyBallWithTimeVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface EnergyBallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    long countByExample(EnergyBallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int deleteByExample(EnergyBallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int insert(EnergyBall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int insertSelective(EnergyBall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    List<EnergyBall> selectByExample(EnergyBallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    EnergyBall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") EnergyBall record, @Param("example") EnergyBallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByExample(@Param("record") EnergyBall record, @Param("example") EnergyBallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByPrimaryKeySelective(EnergyBall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table energy_ball
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    int updateByPrimaryKey(EnergyBall record);

    /**
     * 根据 id 与时间模糊查询
     * @param energyBallWithTimeVo
     * @return
     */
    List<EnergyBall> selectByTimeFuzzyQuery(EnergyBallWithTimeVo energyBallWithTimeVo);
}