package com.cascv.oas.server.energy.model;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;

@Component
public class EnergyBall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.id
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.user_id
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.point_source
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private Integer pointSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private BigDecimal point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.power_source
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private Integer powerSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.power
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private BigDecimal power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_ball.status
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.id
     *
     * @return the value of energy_ball.id
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.id
     *
     * @param id the value for energy_ball.id
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.user_id
     *
     * @return the value of energy_ball.user_id
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.user_id
     *
     * @param userId the value for energy_ball.user_id
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.point_source
     *
     * @return the value of energy_ball.point_source
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public Integer getPointSource() {
        return pointSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.point_source
     *
     * @param pointSource the value for energy_ball.point_source
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setPointSource(Integer pointSource) {
        this.pointSource = pointSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.point
     *
     * @return the value of energy_ball.point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public BigDecimal getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.point
     *
     * @param point the value for energy_ball.point
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setPoint(BigDecimal point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.power_source
     *
     * @return the value of energy_ball.power_source
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public Integer getPowerSource() {
        return powerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.power_source
     *
     * @param powerSource the value for energy_ball.power_source
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setPowerSource(Integer powerSource) {
        this.powerSource = powerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.power
     *
     * @return the value of energy_ball.power
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public BigDecimal getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.power
     *
     * @param power the value for energy_ball.power
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setPower(BigDecimal power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_ball.status
     *
     * @return the value of energy_ball.status
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_ball.status
     *
     * @param status the value for energy_ball.status
     *
     * @mbg.generated Wed Aug 22 11:03:27 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "EnergyBall{" +
                "id=" + id +
                ", userId=" + userId +
                ", pointSource=" + pointSource +
                ", point=" + point +
                ", powerSource=" + powerSource +
                ", power=" + power +
                ", status=" + status +
                '}';
    }
}