package com.cascv.oas.server.energy.model;

import java.math.BigDecimal;

public class EnergySourcePower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.id
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.source_code
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private Integer sourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.source_name
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private String sourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.type
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.power_single
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private Integer powerSingle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.power_total
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private Integer powerTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.power_increase_speed
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private BigDecimal powerIncreaseSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.power_increase_speed_unit_name
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private String powerIncreaseSpeedUnitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.power_increase_speed_unit_value
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private Integer powerIncreaseSpeedUnitValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_source_power.power_max_each_ball
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    private Integer powerMaxEachBall;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.id
     *
     * @return the value of energy_source_power.id
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.id
     *
     * @param id the value for energy_source_power.id
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.source_code
     *
     * @return the value of energy_source_power.source_code
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public Integer getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.source_code
     *
     * @param sourceCode the value for energy_source_power.source_code
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setSourceCode(Integer sourceCode) {
        this.sourceCode = sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.source_name
     *
     * @return the value of energy_source_power.source_name
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.source_name
     *
     * @param sourceName the value for energy_source_power.source_name
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.type
     *
     * @return the value of energy_source_power.type
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.type
     *
     * @param type the value for energy_source_power.type
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.power_single
     *
     * @return the value of energy_source_power.power_single
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public Integer getPowerSingle() {
        return powerSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.power_single
     *
     * @param powerSingle the value for energy_source_power.power_single
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setPowerSingle(Integer powerSingle) {
        this.powerSingle = powerSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.power_total
     *
     * @return the value of energy_source_power.power_total
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public Integer getPowerTotal() {
        return powerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.power_total
     *
     * @param powerTotal the value for energy_source_power.power_total
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setPowerTotal(Integer powerTotal) {
        this.powerTotal = powerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.power_increase_speed
     *
     * @return the value of energy_source_power.power_increase_speed
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public BigDecimal getPowerIncreaseSpeed() {
        return powerIncreaseSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.power_increase_speed
     *
     * @param powerIncreaseSpeed the value for energy_source_power.power_increase_speed
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setPowerIncreaseSpeed(BigDecimal powerIncreaseSpeed) {
        this.powerIncreaseSpeed = powerIncreaseSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.power_increase_speed_unit_name
     *
     * @return the value of energy_source_power.power_increase_speed_unit_name
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public String getPowerIncreaseSpeedUnitName() {
        return powerIncreaseSpeedUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.power_increase_speed_unit_name
     *
     * @param powerIncreaseSpeedUnitName the value for energy_source_power.power_increase_speed_unit_name
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setPowerIncreaseSpeedUnitName(String powerIncreaseSpeedUnitName) {
        this.powerIncreaseSpeedUnitName = powerIncreaseSpeedUnitName == null ? null : powerIncreaseSpeedUnitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.power_increase_speed_unit_value
     *
     * @return the value of energy_source_power.power_increase_speed_unit_value
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public Integer getPowerIncreaseSpeedUnitValue() {
        return powerIncreaseSpeedUnitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.power_increase_speed_unit_value
     *
     * @param powerIncreaseSpeedUnitValue the value for energy_source_power.power_increase_speed_unit_value
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setPowerIncreaseSpeedUnitValue(Integer powerIncreaseSpeedUnitValue) {
        this.powerIncreaseSpeedUnitValue = powerIncreaseSpeedUnitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_source_power.power_max_each_ball
     *
     * @return the value of energy_source_power.power_max_each_ball
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public Integer getPowerMaxEachBall() {
        return powerMaxEachBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_source_power.power_max_each_ball
     *
     * @param powerMaxEachBall the value for energy_source_power.power_max_each_ball
     *
     * @mbg.generated Mon Aug 27 18:14:38 CST 2018
     */
    public void setPowerMaxEachBall(Integer powerMaxEachBall) {
        this.powerMaxEachBall = powerMaxEachBall;
    }
}