app:
  name: oas
  version: 1.0.0
  copyrightYear: 2018
  addressEnabled: false

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    mode: HTML
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  messages:
    basename: i18n/messages
  profiles: 
    active: druid

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cascv: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEbabled: true
    captchaType: math
  cookie:
    domain: 
    path: /
    httpOnly: true
    maxAge: 30
  session:
    # default 30 minutes
    expireTime: -100000000
    # interval syn session to db(default 1 minutes)
    dbSyncPeriod: 1
    # interval to validate session(default 10 minutes)
    validationInterval: 10
    sessionCount: 1
    kickoutUrl: "/kickout"
  cache:
    prefix: "shiro"

server:
  port: 8080
  session-timeout: -100000000 #1800

media:
  server:
    imageHost : http://oas.cascv.com:8080

wallet:
  providers:
    ropsten: "https://ropsten.infura.io/16897256b61d42689d088039a362a61b"
    mainnet: "https://mainnet.infura.io/16897256b61d42689d088039a362a61b"
  defaultNet: ropsten
  
  token: "0x6Fe2542DC2B902141C14F085A646A38cDF0BeecF"
  contracts[0]: 
    address: "0x6Fe2542DC2B902141C14F085A646A38cDF0BeecF"
mail:
  rootMail: "3602745100@qq.com"
  password: "hgmwayjbwmomcjdd"
  name: "3602745100@qq.com"
  subject: "密码重置"