app:
  name: oas
  version: 1.0.0
  copyrightYear: 2018
  addressEnabled: false

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    mode: HTML
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  messages:
    basename: i18n/messages
  profiles: 
    active: druid

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cascv: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEbabled: true
    captchaType: math
  cookie:
    domain: 
    path: /
    httpOnly: true
    maxAge: 30
  session:
    # default 30 minutes
    expireTime: -100000000
    # interval syn session to db(default 1 minutes)
    dbSyncPeriod: 1
    # interval to validate session(default 10 minutes)
    validationInterval: 10
    sessionCount: 1
    kickoutUrl: "/kickout"
  cache:
    prefix: "shiro"

server:
  port: 443
  session-timeout: -100000000 #1800
  ssl:
    key-store-type: PKCS12
    key-store: classpath:215096020960791.pfx
    key-store-password: 215096020960791
    key-alias: alias
media:
  server:
    imageHost : https://oas.cascv.com

mail:
  mailBean:
    rootMail: "oases@oases.pro"
    password: "Epc588"
    name: "oases@oases.pro"
    subject: "邮箱验证"

quartz:
  properties:
    org.quartz.scheduler.instanceName: "EtherScheduler"
    org.quartz.scheduler.instanceId: "AUTO"
    # thread pool
    org.quartz.threadPool.class: "org.quartz.simpl.SimpleThreadPool"
    org.quartz.threadPool.threadCount: 20
    org.quartz.threadPool.threadPriority: 5
    # JobStore
    org.quartz.jobStore.class: "org.quartz.simpl.RAMJobStore"
    
exchangeHourseuUrl : http://www.zzex.pro/m/allticker
